language: go
dist: bionic
notifications:
  email: true
go:
  - 1.13.x
addons:
  apt:
    packages:
      - libseccomp-dev
      - parallel
      - uidmap
      - pigz
before_install:
  - pushd /
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -u github.com/go-bindata/go-bindata/go-bindata
  - popd
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Run e2e Tests
      script:
        - make install
        - ./contrib/e2e-dockerfiles-build-test.sh
      env:
        - STATE_DIR=$HOME/img
    - stage: Build Release
      script:
        - make release
      before_deploy:
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/img-linux-amd64
          - cross/img-linux-amd64.md5
          - cross/img-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "DtPAY0E0z9gizFY6Nv6cCeWv+lAPXT23yvElmXemm4bANGVbydw4Gltv0CEOlW0YCYHxC8CtR+y/h40ADh4GXmLvmSq/U7QxHxWqr8HEF5ui2YgInQGrJ6DKxcpiIwDT/3qJldwlCZoY82PRaw1R0VQJwH+nLQfheXZ4cd2ltK5e2TVV5yIUjWZ0zn/G/qJM4jrqvkm+Zx2GiFhg5PbtgnNgm77exc6hW8oY6fll+Veqtz9J3OAq8JJMgHzIoIP5IHxBU1yDMyhv2aB6XTyX3FYev+uy/pPzAqWIJgMZLDDph/Gvji0JDNmDo5FuFUwut7Q/1P82DHK467G+WMlDj4S2C3btfIc0qBvkkXb0kx4A+JjYt4pgNk2gzBMHe6RWhdRT199Amt26yuNO/xGO7zLJDlv0ScpuwNyRTsBUcC4n6nr26alxjBcJni3VhOYKz+Mn+YEO3BtYJt3vw4VECr7sN3HMu+CW8JBgwdQ1YrOES0C2nXecAUT1CAkE+qIY2gAm3t5qvUg1x47wmAHnm9E2vzcu+OpYRDWcvirX1ZL5iJLJ07Ai4GaV2ljDS0n5Br1vkm2b3cS8Xqo0Ut6ok6YTDmRKCRVvCuEXItWwI9a9KQU06QPxr7hbeUBbPqi/o8UMmxs69mgVlZeXvqdORk1ef1aNnqf/0baHa5r1tkA="
