on:
  push:
    tags:
      - v*
name: make release
jobs:
  makerelease:
    name: make release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install deps
        run: |
          apt install -y \
            libseccomp-dev \
            parallel \
            uidmap \
            pigz \
            --no-install-recommends
        shell: bash
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: install go tools
        run: |
          go get golang.org/x/lint/golint
          go get honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/go-bindata/go-bindata/go-bindata
        shell: bash
      - name: make release
        run: make release
        shell: bash
      - name: upload assets
        uses: docker://r.j3ss.co/github-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: bash
          args: -c "upload-assets ./cross/*"
      - name: update release body
        uses: docker://r.j3ss.co/pepper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: sh
          args: -c "pepper release --repo $GITHUB_REPOSITORY -d --nouser"
